LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Models/LvnModel12010900024.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvnBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LvnK22CNT1Lesson07DbEntities : DbContext
    {
        public LvnK22CNT1Lesson07DbEntities()
            : base("name=LvnK22CNT1Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lvnKhoa> lvnKhoa { get; set; }
        public virtual DbSet<lvnSinhVien> lvnSinhVien { get; set; }
    }
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Models/LvnModel12010900024.Designer.cs
// T4 code generation is enabled for model 'D:\Thư mục mới\LvnBaiKiemTraGK\LvnBaiKiemTraGK\Models\LvnModel12010900024.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Models/lvnKhoa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lvnKhoa()
        {
            this.lvnSinhVien = new HashSet<lvnSinhVien>();
        }
    
        public string LvnMaKH { get; set; }
        public string LvnTenKH { get; set; }
        public Nullable<bool> Lvn_Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lvnSinhVien> lvnSinhVien { get; set; }
    }
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Models/lvnSinhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvnSinhVien
    {
        public string LvnMaSV { get; set; }
        public string LvnHoSV { get; set; }
        public string LvnTenSV { get; set; }
        public Nullable<System.DateTime> LvnNgaySinh { get; set; }
        public Nullable<bool> LvnPhai { get; set; }
        public string LvnPhone { get; set; }
        public string LvnEmail { get; set; }
        public string LvnMaKH { get; set; }
    
        public virtual lvnKhoa lvnKhoa { get; set; }
    }
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LvnBaiKiemTraGK.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Controllers/LvnKhoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LvnBaiKiemTraGK.Models;

namespace LvnBaiKiemTraGK.Controllers
{
    public class LvnKhoasController : Controller
    {
        private LvnK22CNT1Lesson07DbEntities db = new LvnK22CNT1Lesson07DbEntities();

        // GET: LvnKhoas
        public ActionResult LvnIndex()
        {
            return View(db.lvnKhoa.ToList());
        }

        // GET: LvnKhoas/Details/5
        public ActionResult LvnDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lvnKhoa lvnKhoa = db.lvnKhoa.Find(id);
            if (lvnKhoa == null)
            {
                return HttpNotFound();
            }
            return View(lvnKhoa);
        }

        // GET: LvnKhoas/Create
        public ActionResult LvnCreate()
        {
            return View();
        }

        // POST: LvnKhoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult  LvnCreate([Bind(Include = "LvnMaKH,LvnTenKH,Lvn_Trang_Thai")] lvnKhoa lvnKhoa)
        {
            if (ModelState.IsValid)
            {
                db.lvnKhoa.Add(lvnKhoa);
                db.SaveChanges();
                return RedirectToAction("LvnIndex");
            }

            return View(lvnKhoa);
        }

        // GET: LvnKhoas/Edit/5
        public ActionResult LvnEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lvnKhoa lvnKhoa = db.lvnKhoa.Find(id);
            if (lvnKhoa == null)
            {
                return HttpNotFound();
            }
            return View(lvnKhoa);
        }

        // POST: LvnKhoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LvnEdit([Bind(Include = "LvnMaKH,LvnTenKH,Lvn_Trang_Thai")] lvnKhoa lvnKhoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lvnKhoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LvnIndex");
            }
            return View(lvnKhoa);
        }

        // GET: LvnKhoas/Delete/5
        public ActionResult LvnDelete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lvnKhoa lvnKhoa = db.lvnKhoa.Find(id);
            if (lvnKhoa == null)
            {
                return HttpNotFound();
            }
            return View(lvnKhoa);
        }

        // POST: LvnKhoas/Delete/5
        [HttpPost, ActionName("LvnDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            lvnKhoa lvnKhoa = db.lvnKhoa.Find(id);
            db.lvnKhoa.Remove(lvnKhoa);
            db.SaveChanges();
            return RedirectToAction("LvnIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Lưu Viết Nam";
}
<h2>@ViewBag.Title.</h2>
<h3>Bài Thi giữa kì của Lưu Viết Nam- cam kết  không đạo văn haha</h3>

<address>
    K22CNT1 - Môn lập trình ứng dụng web với công nghệ ASP.Net MVC5
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:luunam990@gmail.com">luunam990@gmail.com</a><br />
    <strong>Cá nhân:</strong> <a href="mailto:luunam87654@gmail.com">luunam87654@gmail.com</a>
</address>

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/LvnKhoas/LvnCreate.cshtml
@model LvnBaiKiemTraGK.Models.lvnKhoa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>lvnKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LvnMaKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LvnMaKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LvnMaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LvnTenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LvnTenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LvnTenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lvn_Trang_Thai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Lvn_Trang_Thai)
                    @Html.ValidationMessageFor(model => model.Lvn_Trang_Thai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "LvnIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/LvnKhoas/LvnDelete.cshtml
@model LvnBaiKiemTraGK.Models.lvnKhoa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>lvnKhoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LvnTenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LvnTenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lvn_Trang_Thai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lvn_Trang_Thai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "LvnIndex")
        </div>
    }
</div>

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/LvnKhoas/LvnDetails.cshtml
@model LvnBaiKiemTraGK.Models.lvnKhoa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>lvnKhoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LvnTenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LvnTenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lvn_Trang_Thai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lvn_Trang_Thai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LvnMaKH }) |
    @Html.ActionLink("Back to List", "LvnIndex")
</p>

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/LvnKhoas/LvnEdit.cshtml
@model LvnBaiKiemTraGK.Models.lvnKhoa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>lvnKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LvnMaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.LvnTenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LvnTenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LvnTenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lvn_Trang_Thai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Lvn_Trang_Thai)
                    @Html.ValidationMessageFor(model => model.Lvn_Trang_Thai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "LvnIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/LvnKhoas/LvnIndex.cshtml
@model IEnumerable<LvnBaiKiemTraGK.Models.lvnKhoa>

@{
    ViewBag.Title = "LvnIndex";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Lvn:Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LvnTenKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lvn_Trang_Thai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LvnTenKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lvn_Trang_Thai)
        </td>
        <td>
            @Html.ActionLink("Lvn:Edit", "LvnEdit", new { id=item.LvnMaKH.Trim() }) |
            @Html.ActionLink("Lvn:Details", "LvnDetails", new { id=item.LvnMaKH.Trim( }) |
            @Html.ActionLink("Lvn:Delete", "LvnDelete", new { id=item.LvnMaKH.Trim( })
        </td>
    </tr>
}

</table>

LvnLesson09/LvnBaiKiemTraGK/LvnBaiKiemTraGK/Views/Shared/_LvnLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lưu Viết Nam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lưu Viết Nam", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("LVN:khoa", "LvnIndex", "LvnKhoas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>